name: Build SDL on macOS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Xcode
        uses: actions/setup-xcode@v3
        with:
          xcode-version: '14.2' # Ajusta la versión según sea necesario
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install dependencies
        run: brew install cmake
      - name: Build SDL
        run: |
          mkdir build
          cd build
          cmake ..
          make
