name: CI

on: [push, pull_request]

jobs:
  
  windows-msvc:
      name: Windows (MSVC)
      runs-on: windows-latest
      env:
        SDL_VERSION: 2.26.0
      steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
  
      - name: Cache SDL
        uses: actions/cache@v2
        env:
          cache-name: cache-sdl
        with:
          path: C:\SDL
          key: ${{ runner.os }}-build-${{ env.cache-name }}
  
      - name: Download SDL if not cached
        run: |
          if (-Not (Test-Path C:\SDL))
          {
              Invoke-WebRequest "https://github.com/libsdl-org/SDL/releases/download/release-$env:SDL_VERSION/SDL2-devel-$env:SDL_VERSION-VC.zip" -OutFile C:\SDL.zip
              Expand-Archive C:\SDL.zip -DestinationPath C:\
          }
  
      - name: CMake configure (Debug)
        run: |
          $env:LDFLAGS =  "/LIBPATH:C:\SDL2-$env:SDL_VERSION\lib\x86 "
          cmake -B debug -G "Visual Studio 17 2022" . -DCMAKE_BUILD_TYPE=Debug `
            -A Win32 `
            -DSDL2_INCLUDE_DIRS="C:\SDL2-$env:SDL_VERSION\include" `
            -DSDL2_LIBRARIES="SDL2;SDL2main"
  
      - name: Build (Debug)
        run: cmake --build debug
  
      - name: CMake configure (Release)
        run: |
          $env:LDFLAGS =  "/LIBPATH:C:\SDL2-$env:SDL_VERSION\lib\x86 "
          cmake -B release -G "Visual Studio 17 2022" . -DCMAKE_BUILD_TYPE=Release `
            -A Win32 `
            -DSDL2_INCLUDE_DIRS="C:\SDL2-$env:SDL_VERSION\include" `
            -DSDL2_LIBRARIES="SDL2;SDL2main"
  
      - name: Build (Release)
        run: cmake --build release
